In [16]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

In [17]:
df = pd.read_csv(r'C:\Users\LENOVO\Desktop\codsoft\advertising.csv')

In [18]:
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [19]:
df.isna().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

no null value and all in the numeric so nno need to preprocessig and all frature are important so so needed to feature extraction

In [20]:
df.shape

(200, 4)

In [21]:
df.columns

Index(['TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

In [22]:
X = df.drop(columns = ['Sales'],axis = 1)
y = df['Sales']

sales is in continuous value so we can apply linear regression model

linear regression need standerdlization

In [23]:
from sklearn.preprocessing import StandardScaler

In [26]:
scaler = StandardScaler()
cols_to_scale = ['TV', 'Radio', 'Newspaper']
df[cols_to_scale]  = scaler.fit_transform(df[cols_to_scale])

In [27]:
df.head()

         TV     Radio  Newspaper  Sales
0  0.969852  0.981522   1.778945   22.1
1 -1.197376  1.082808   0.669579   10.4
2 -1.516155  1.528463   1.783549   12.0
3  0.052050  1.217855   1.286405   16.5
4  0.394182 -0.841614   1.281802   17.9

In [35]:
X = df.drop(columns = ['Sales'],axis = 1)
y = df['Sales']

In [36]:
X

           TV     Radio  Newspaper
0    0.969852  0.981522   1.778945
1   -1.197376  1.082808   0.669579
2   -1.516155  1.528463   1.783549
3    0.052050  1.217855   1.286405
4    0.394182 -0.841614   1.281802
..        ...       ...        ...
195 -1.270941 -1.321031  -0.771217
196 -0.617035 -1.240003  -1.033598
197  0.349810 -0.942899  -1.111852
198  1.594565  1.265121   1.640850
199  0.993206 -0.990165  -1.005979

[200 rows x 3 columns]

In [28]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [37]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [38]:
y_pred = model.predict(X_test)

In [39]:
r2 = r2_score(y_test,y_pred)
r2

0.9031541781049791